# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from __future__ import annotations
from argparse import ArgumentParser, Namespace
from collections.abc import Sequence
from pathlib import Path
from pybind11_stubgen.parser.interface import IParser
from pybind11_stubgen.parser.mixins.error_handlers import IgnoreAllErrors, IgnoreInvalidExpressionErrors, IgnoreInvalidIdentifierErrors, IgnoreUnresolvedNameErrors, LogErrors, LoggerData, SuggestCxxSignatureFix, TerminateOnFatalErrors
from pybind11_stubgen.parser.mixins.filter import FilterClassMembers, FilterInvalidIdentifiers, FilterPybind11ViewClasses, FilterPybindInternals, FilterTypingModuleAttributes
from pybind11_stubgen.parser.mixins.fix import FixBuiltinTypes, FixCurrentModulePrefixInTypeNames, FixMissingEnumMembersAnnotation, FixMissingFixedSizeImport, FixMissingImports, FixMissingNoneHashFieldAnnotation, FixMissing__all__Attribute, FixMissing__future__AnnotationsImport, FixNumpyArrayDimAnnotation, FixNumpyArrayDimTypeVar, FixNumpyArrayFlags, FixNumpyArrayRemoveParameters, FixNumpyDtype, FixPEP585CollectionNames, FixPybind11EnumStrDoc, FixRedundantBuiltinsAnnotation, FixRedundantMethodsFromBuiltinObject, FixScipyTypeArguments, FixTypingTypeNames, FixValueReprRandomAddress, OverridePrintSafeValues, RemoveSelfAnnotation, ReplaceReadWritePropertyWithField, RewritePybind11EnumValueRepr
from pybind11_stubgen.parser.mixins.parse import BaseParser, ExtractSignaturesFromPybind11Docstrings, ParserDispatchMixin
from pybind11_stubgen.printer import Printer
from pybind11_stubgen.structs import QualifiedName
from pybind11_stubgen.writer import Writer
from typing import Any
from dataclasses import dataclass
import importlib
import logging
import re

@dataclass
class CLIArgs(Namespace):
def arg_parser() -> ArgumentParser:
    ...

def stub_parser_from_args(args: CLIArgs) -> IParser:
    ...

def main(argv: Sequence[str] | None) -> None:
    ...

def to_output_and_subdir(output_dir: str, module_name: str, root_suffix: str | None) -> tuple[Path, Path | None]:
    ...

def run(parser: IParser, printer: Printer, module_name: str, out_dir: Path, sub_dir: Path | None, dry_run: bool, writer: Writer) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import __future__
import importlib
import logging
import re
import argparse
import collections
import collections.abc
import pathlib
import abc
import types
import typing
import sys
import logging.getLogger
import builtins
import inspect
import ast
import dataclasses